[workspace]
resolver = "2"
members = [ "server" ]

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
once_cell = "1"
anyhow = "1"
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.12", features = ["json"] }